/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmcollection_free: (a: number, b: number) => void;
export const __wbg_wasmdb_free: (a: number, b: number) => void;
export const chunk: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmcollection_delete: (a: number, b: number, c: number, d: number) => void;
export const wasmcollection_get: (a: number, b: number, c: number, d: number) => void;
export const wasmcollection_hybridSearch: (a: number, b: number, c: number) => void;
export const wasmcollection_isEmpty: (a: number) => number;
export const wasmcollection_len: (a: number) => number;
export const wasmcollection_refit: (a: number, b: number) => void;
export const wasmcollection_scroll: (a: number, b: number, c: number) => void;
export const wasmcollection_search: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmcollection_searchText: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmcollection_stats: (a: number, b: number) => void;
export const wasmcollection_upsert: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const wasmcollection_upsertBatch: (a: number, b: number, c: number) => void;
export const wasmcollection_upsertText: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const wasmdb_collection: (a: number, b: number, c: number, d: number) => void;
export const wasmdb_createAlias: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasmdb_createCollection: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmdb_deleteAlias: (a: number, b: number, c: number, d: number) => void;
export const wasmdb_deleteCollection: (a: number, b: number, c: number, d: number) => void;
export const wasmdb_formatVersion: (a: number) => number;
export const wasmdb_fromBytes: (a: number, b: number, c: number) => void;
export const wasmdb_listCollections: (a: number, b: number) => void;
export const wasmdb_memory: () => number;
export const wasmdb_serialize: (a: number, b: number) => void;
export const wasmdb_vacuum: (a: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
