//! Server parity corpus (SPEC-005 acceptance 1, EMB-002): the fixture in
//! `fixtures/embedding_parity.json` was generated by compiling the Vectorizer
//! server's UNMODIFIED provider sources (`vectorizer/src/embedding/providers/
//! {bm25,tfidf,bag_of_words,char_ngram}.rs`) and dumping, for a fixed corpus,
//! each provider's embedding of 3 queries + all 8 documents. VecLite's
//! vendored providers must reproduce every component within 1e-5 — any drift
//! in tokenizer, vocabulary construction, or scoring math is breaking.

#![cfg(not(target_arch = "wasm32"))]

use veclite::build_provider;

const FIXTURE: &str = include_str!("fixtures/embedding_parity.json");
const TOLERANCE: f32 = 1e-5;

#[test]
fn vendored_providers_match_the_server_within_tolerance() {
    let doc: serde_json::Value =
        serde_json::from_str(FIXTURE).unwrap_or_else(|e| panic!("fixture: {e}"));
    let corpus: Vec<String> = doc["corpus"]
        .as_array()
        .unwrap_or_else(|| panic!("corpus"))
        .iter()
        .map(|v| v.as_str().unwrap_or_default().to_owned())
        .collect();
    let queries: Vec<String> = doc["queries"]
        .as_array()
        .unwrap_or_else(|| panic!("queries"))
        .iter()
        .map(|v| v.as_str().unwrap_or_default().to_owned())
        .collect();
    let corpus_refs: Vec<&str> = corpus.iter().map(String::as_str).collect();

    for provider in ["bm25", "tfidf", "bow", "char_ngram"] {
        let expected = doc[provider]
            .as_array()
            .unwrap_or_else(|| panic!("{provider} vectors"));
        let mut emb = build_provider(provider, 64).unwrap_or_else(|e| panic!("{e}"));
        emb.fit(&corpus_refs).unwrap_or_else(|e| panic!("{e}"));

        // Fixture layout: the 3 queries, then the 8 corpus documents.
        let inputs: Vec<&str> = queries
            .iter()
            .map(String::as_str)
            .chain(corpus.iter().map(String::as_str))
            .collect();
        assert_eq!(expected.len(), inputs.len(), "{provider}: fixture shape");
        for (text, want) in inputs.iter().zip(expected) {
            let got = emb.embed(text).unwrap_or_else(|e| panic!("{e}"));
            let want: Vec<f32> = want
                .as_array()
                .unwrap_or_else(|| panic!("vector"))
                .iter()
                .map(|v| v.as_f64().unwrap_or_default() as f32)
                .collect();
            assert_eq!(got.len(), want.len(), "{provider}: dimension");
            for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
                assert!(
                    (g - w).abs() <= TOLERANCE,
                    "{provider}: {text:?} component {i}: got {g}, server {w}"
                );
            }
        }
    }
}
