//! Graceful degradation without the ONNX feature (SPEC-005 EMB-023). A
//! `.veclite` file whose collection declares a `fastembed:*` provider MUST open
//! on a build WITHOUT the `onnx` feature: vector-level reads and searches work,
//! and only text operations fail as `UnsupportedProvider`.
//!
//! This test runs on the BASE build (no `onnx`). It reads the fixture written by
//! `onnx_embeddings::write_degradation_fixture` (an onnx build). When the onnx
//! feature IS on, the provider resolves and text ops would succeed, so the
//! typed-failure assertions are skipped there.

use std::path::Path;

use veclite::{Point, VecLite};

fn fixture() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/onnx_degradation.veclite")
}

#[test]
fn onnx_file_opens_and_serves_vectors_without_the_model() {
    let path = fixture();
    if !path.is_file() {
        // The fixture is generated by the onnx build (see onnx_embeddings.rs).
        // Without it there is nothing to assert; fail loudly so it is not a
        // silent skip in the onnx CI that regenerates it.
        panic!(
            "missing fixture {} — regenerate with: cargo test -p hivellm-veclite --features onnx -- \
             --ignored write_degradation_fixture",
            path.display()
        );
    }

    // Work on a copy: opening read-write journals mutations to a WAL beside the
    // file, so never touch the committed fixture.
    let work = std::env::temp_dir().join(format!(
        "veclite-onnx-degrade-{}.veclite",
        std::process::id()
    ));
    let _ = std::fs::remove_file(&work);
    std::fs::copy(&path, &work).unwrap_or_else(|e| panic!("copy fixture: {e}"));

    // Opening MUST succeed even though `fastembed:*` is unavailable on this build.
    let db = VecLite::open(&work).unwrap_or_else(|e| panic!("open onnx file: {e}"));
    let c = db
        .collection("docs")
        .unwrap_or_else(|e| panic!("collection: {e}"));
    assert!(!c.is_empty(), "expected the persisted vectors");

    // Vector-level reads work: fetch a stored dense vector and search with it.
    let Some(cat) = c.get("cat").unwrap_or_else(|e| panic!("get: {e}")) else {
        panic!("cat missing from fixture")
    };
    assert_eq!(cat.vector.len(), 384, "MiniLM vectors are 384-dim");

    let hits = c
        .query(&cat.vector)
        .limit(1)
        .run()
        .unwrap_or_else(|e| panic!("vector search: {e}"));
    assert_eq!(
        hits[0].id, "cat",
        "vector search must return the nearest stored point"
    );

    // A caller-supplied BYO vector upsert + search also works (vector ops are
    // provider-independent).
    c.upsert(Point::new("probe", cat.vector.clone()))
        .unwrap_or_else(|e| panic!("byo upsert: {e}"));
    assert!(c.len() >= 2);

    // Text operations fail typed — only on a build without the model.
    #[cfg(not(feature = "onnx"))]
    {
        let Err(e) = c.search_text("a pet that meows", 1) else {
            panic!("search_text must fail without the onnx model");
        };
        assert!(
            matches!(e, veclite::VecLiteError::UnsupportedProvider { .. }),
            "expected UnsupportedProvider, got {e:?}"
        );

        let Err(e2) = c.upsert_text_batch(vec![("t".into(), "some text".into(), None)]) else {
            panic!("upsert_text must fail without the onnx model");
        };
        assert!(
            matches!(e2, veclite::VecLiteError::UnsupportedProvider { .. }),
            "expected UnsupportedProvider, got {e2:?}"
        );
    }

    drop(db);
    let _ = std::fs::remove_file(&work);
}
