/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** `open` / `openSync` options (mirrors `OpenOptions`, NODE-010). */
export interface OpenOpts {
  readOnly?: boolean
  /** `"full" | "normal" | "off"`. */
  durability?: string
  /** Force mmap on/off (default: auto over 64 MiB). */
  mmap?: boolean
  /** In-RAM index budget in bytes before a mapped collection scans (STG-064). */
  memoryBudget?: number
}
/** HNSW tuning (mirrors `HnswOptions`). */
export interface HnswOpts {
  m?: number
  efConstruction?: number
  efSearch?: number
}
/** `createCollection` options (mirrors `CollectionOptions`). */
export interface CollectionOpts {
  dimension: number
  /** `"cosine" | "euclidean" | "dotproduct"` (default cosine). */
  metric?: string
  /** Scalar-quantization bit depth; 0 or absent = no quantization. */
  quantizationBits?: number
  hnsw?: HnswOpts
  /** Auto-embed provider id (e.g. `"bm25"`); absent = BYO vectors. */
  autoEmbed?: string
  /** Declared payload indexes as `[key, "keyword"|"integer"|"float"]` pairs. */
  payloadIndexes?: Array<Array<string>>
}
/** `search` / `searchSync` options. */
export interface SearchOpts {
  limit?: number
  efSearch?: number
  withPayload?: boolean
  withVector?: boolean
  /** A Qdrant-style filter document (SPEC-006), as a plain JS object. */
  filter?: any
}
/** One search hit projected to JS (NODE-011). */
export interface JsHit {
  id: string
  score: number
  payload?: any
  vector?: Float32Array
}
/** A point for `upsertBatch` (BYO vectors): id + vector + optional payload. */
export interface JsPoint {
  id: string
  vector: Float32Array
  payload?: any
}
/** Open an ephemeral in-memory database (FR-02) — no file, identical API. */
export declare function memory(): Database
/** Open (or create) a file-backed database off the event loop (NODE-011). */
export declare function open(path: string, options?: OpenOpts | undefined | null): Promise<Database>
/** Synchronous [`open`] for CLIs/scripts. */
export declare function openSync(path: string, options?: OpenOpts | undefined | null): Database
/** Hybrid query options (SPEC-007). */
export interface HybridOpts {
  dense?: Float32Array
  /** `{ indices: number[], values: number[] }`. */
  sparse?: any
  alpha?: number
  rrfK?: number
  limit?: number
}
/** `scroll` options (SPEC-004 API-022). */
export interface ScrollOpts {
  limit?: number
  offsetId?: string
  filter?: any
}
/** One page of a `scroll`. */
export interface JsScrollPage {
  points: Array<JsHit>
  nextCursor?: string
}
/** Collection statistics projected to JS. */
export interface JsStats {
  name: string
  dimension: number
  len: number
  tombstones: number
  autoEmbed: boolean
}
/**
 * A VecLite database handle (SPEC-004 §1). `VecLite` is internally `Arc`, so
 * cloning it into blocking tasks is cheap. The handle sits behind an
 * `Option` so `close()` can drop it deterministically (NODE-013) — releasing
 * the advisory file lock and running the close-time checkpoint — rather than
 * waiting for JS garbage collection.
 */
export declare class Database {
  /** Create a collection (CORE-020). Async: runs off the event loop. */
  createCollection(name: string, options: CollectionOpts): Promise<Collection>
  createCollectionSync(name: string, options: CollectionOpts): Collection
  /** Get a collection handle by name or alias (CORE-051). */
  collection(name: string): Collection
  /** List collection names. */
  listCollections(): Array<string>
  /** Delete a collection (CORE-021). */
  deleteCollection(name: string): void
  /** Flush acked state to disk (WAL-030b). */
  checkpoint(): Promise<void>
  /** Write a standalone compacted copy at `path` (STG-070). */
  snapshot(path: string): Promise<void>
  /** Reclaim dead space in place (STG-071). */
  vacuum(): Promise<void>
  /** The on-disk format version this build reads/writes (NFR-11). */
  formatVersion(): number
  /**
   * Flush and close (NODE-013): checkpoint, then drop this handle so the
   * advisory file lock releases immediately (not on GC). Idempotent — a
   * second call, and any op after close, is a no-op / `Closed`. Note: a
   * still-referenced `Collection` keeps the file open, so drop collections
   * before reopening the same path in-process.
   */
  close(): Promise<void>
}
/** A collection handle (SPEC-004 §4). Cheap to clone (Arc inside). */
export declare class Collection {
  /** Number of live vectors. */
  len(): number
  /** Whether the collection holds no live vectors. */
  isEmpty(): boolean
  /** Insert-or-replace one point (API-020). Async: off the event loop. */
  upsert(id: string, vector: Float32Array, payload?: any | undefined | null): Promise<void>
  /** Synchronous [`upsert`] — `vector` crosses zero-copy (NODE-012). */
  upsertSync(id: string, vector: Float32Array, payload?: any | undefined | null): void
  /** Insert-or-replace a batch (API-020, one WAL entry). */
  upsertBatch(points: Array<JsPoint>): Promise<void>
  upsertBatchSync(points: Array<JsPoint>): void
  /** Insert-or-replace one text document on an auto-embed collection. */
  upsertText(id: string, text: string, payload?: any | undefined | null): Promise<void>
  upsertTextSync(id: string, text: string, payload?: any | undefined | null): void
  /** k-NN search (API-030). Async: off the event loop. */
  search(query: Float32Array, options?: SearchOpts | undefined | null): Promise<Array<JsHit>>
  /** Synchronous [`search`] — `query` crosses zero-copy (NODE-012). */
  searchSync(query: Float32Array, options?: SearchOpts | undefined | null): Array<JsHit>
  /** Embed `query` with the collection's provider and search (SPEC-005 §4). */
  searchText(query: string, options?: SearchOpts | undefined | null): Promise<Array<JsHit>>
  searchTextSync(query: string, options?: SearchOpts | undefined | null): Array<JsHit>
  /** Hybrid dense+sparse search with RRF fusion (SPEC-007). */
  hybridSearch(options: HybridOpts): Array<JsHit>
  /**
   * Cursor-based pagination over live points in stable slot order
   * (API-022). Pass `offsetId` from a prior page's `nextCursor`.
   */
  scroll(options?: ScrollOpts | undefined | null): JsScrollPage
  /** Fetch a point by id (API-021); `null` when absent. */
  get(id: string): JsHit | null
  /** Delete a point by id (API-022); `true` if it existed. */
  delete(id: string): boolean
  /** Collection statistics (FR-08/13). */
  stats(): JsStats
}
