//! Binding-conformance corpus runner (SPEC-015 §3, TST-020..023; DAG T4.5).
//!
//! One YAML corpus in `tests/conformance/corpus/` describes operation sequences
//! and their expected outcomes. This is the **Rust reference runner** — it
//! defines the golden outcomes the Python and Node runners must reproduce
//! bit-for-bit (orderings/id-sets exact, scores within 1e-5, TST-022).
//!
//! Each case runs in one or more *modes*: `memory` (`VecLite::memory`) and/or
//! `file` (a temp-file db). `mode: both` (the default) runs it in both and
//! requires identical outcomes — that is the in-memory ≡ file-backed check
//! (TST-021). A `reopen` step (checkpoint + close + reopen) exercises WAL replay
//! and auto-embed vocabulary determinism, and is only valid in `file` mode.
//!
//! Every expectation is a plain JSON value compared with a numeric-tolerant
//! deep-equal (1e-5), the identical comparison the other-language runners use,
//! so a case that is green here is green everywhere or the binding diverged.
//!
//! The corpus YAML is hand-authored and holds the human-meaningful assertions
//! (`ids`, `error`, `result`, …). Machine golden — per-step scores and lossy
//! round-trips that would be tedious and fragile to hand-compute — live in a
//! committed `golden.json` sidecar that this reference runner emits with
//! `--bless` and every runner then asserts against (TST-022; a diff to it is a
//! behavior change, TST-023).
//!
//! Usage: `cargo xtask conformance [--bless] [corpus_dir]`

use std::path::{Path, PathBuf};

use serde::Deserialize;
use serde_json::{Value, json};
use veclite::chunk::{ChunkOptions, Chunker};
use veclite::{
    CollectionOptions, Durability, Filter, HnswOptions, Metric, OpenOptions, PayloadIndexKind,
    Point, Quantization, SparseVector, VecLite, VecLiteError,
};

const SCORE_TOL: f64 = 1e-5;

/// Name of the committed golden sidecar next to the corpus dir. It holds, per
/// case id, the reference runner's full per-step observation — the machine
/// golden that pins scores and lossy round-trips without hand-computing them
/// (TST-022). Regenerated by `--bless`; a diff to it is a behavior change
/// (TST-023).
const GOLDEN_FILE: &str = "golden.json";

/// Per-case golden: an array of per-step observations (index-aligned with the
/// case's non-`reopen` steps). A failing step's observation is `{"error": CODE}`.
type Golden = std::collections::BTreeMap<String, Vec<Value>>;

// ── Corpus schema ────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct Suite {
    /// Human-readable suite name (also used in failure output).
    suite: String,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    /// Stable id `conf-xxx`, referenced in failure output (TST-022).
    id: String,
    /// One-line description of what the case pins.
    desc: String,
    /// `both` (default) | `memory` | `file`. `both` runs the steps in an
    /// in-memory and a file-backed db and requires identical outcomes.
    #[serde(default = "default_mode")]
    mode: String,
    steps: Vec<Step>,
}

#[derive(Deserialize)]
struct Step {
    /// Operation name (see `execute`).
    op: String,
    /// Operation arguments as a JSON object (absent fields take API defaults).
    #[serde(default)]
    args: Value,
    /// Inline, human-authored assertions (subset-matched). Absent ⇒ the step
    /// must merely succeed; the golden still pins its full observation.
    #[serde(default)]
    expect: Option<Value>,
}

fn default_mode() -> String {
    "both".to_owned()
}

// ── Entry point ──────────────────────────────────────────────────────────────

/// `cargo xtask conformance [--bless] [corpus_dir]`.
pub fn run(args: &[String]) -> i32 {
    let bless = args.iter().any(|a| a == "--bless");
    let dir = args
        .iter()
        .find(|a| !a.starts_with("--"))
        .cloned()
        .unwrap_or_else(default_corpus_dir);
    let dir = PathBuf::from(dir);
    let golden_path = dir.join(GOLDEN_FILE);

    let files = match corpus_files(&dir) {
        Ok(f) if !f.is_empty() => f,
        Ok(_) => {
            eprintln!(
                "[conformance] no *.yaml corpus files under {}",
                dir.display()
            );
            return 1;
        }
        Err(e) => {
            eprintln!("[conformance] cannot read {}: {e}", dir.display());
            return 1;
        }
    };

    // The committed golden the reference asserts against (empty when blessing).
    let golden: Golden = if bless {
        Golden::new()
    } else {
        match load_golden(&golden_path) {
            Ok(g) => g,
            Err(e) => {
                eprintln!(
                    "[conformance] read {}: {e} (run `--bless` to create it)",
                    golden_path.display()
                );
                return 1;
            }
        }
    };

    let mut fresh: Golden = Golden::new();
    let mut total = 0usize;
    let mut failed = 0usize;
    for file in &files {
        let text = match std::fs::read_to_string(file) {
            Ok(t) => t,
            Err(e) => {
                eprintln!("[conformance] read {}: {e}", file.display());
                return 1;
            }
        };
        let suite: Suite = match serde_yaml::from_str(&text) {
            Ok(s) => s,
            Err(e) => {
                eprintln!("[conformance] parse {}: {e}", file.display());
                return 1;
            }
        };
        for case in &suite.cases {
            total += 1;
            match run_case(case, &golden, bless) {
                Ok(observed) => {
                    if bless {
                        fresh.insert(case.id.clone(), observed);
                    }
                }
                Err(e) => {
                    failed += 1;
                    eprintln!(
                        "[conformance] FAIL {} [{}]: {e}\n              ({})",
                        case.id, suite.suite, case.desc
                    );
                }
            }
        }
    }

    if bless {
        if failed != 0 {
            eprintln!("[conformance] {failed}/{total} cases FAILED — refusing to write golden");
            return 1;
        }
        match serde_json::to_string_pretty(&fresh) {
            Ok(mut out) => {
                out.push('\n');
                if let Err(e) = std::fs::write(&golden_path, out) {
                    eprintln!("[conformance] write {}: {e}", golden_path.display());
                    return 1;
                }
                eprintln!(
                    "[conformance] blessed {total} cases → {}",
                    golden_path.display()
                );
                0
            }
            Err(e) => {
                eprintln!("[conformance] serialize golden: {e}");
                1
            }
        }
    } else if failed == 0 {
        eprintln!(
            "[conformance] PASS — {total} cases across {} files",
            files.len()
        );
        0
    } else {
        eprintln!("[conformance] {failed}/{total} cases FAILED");
        1
    }
}

fn load_golden(path: &Path) -> Result<Golden, String> {
    let text = std::fs::read_to_string(path).map_err(|e| e.to_string())?;
    serde_json::from_str(&text).map_err(|e| e.to_string())
}

fn default_corpus_dir() -> String {
    // xtask runs from the workspace root under `cargo xtask`.
    "tests/conformance/corpus".to_owned()
}

fn corpus_files(dir: &Path) -> std::io::Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().and_then(|e| e.to_str()) == Some("yaml") {
            out.push(path);
        }
    }
    out.sort();
    Ok(out)
}

// ── Case execution ───────────────────────────────────────────────────────────

/// Run a case in each of its modes, returning the per-step observations (used to
/// (re)write the golden under `--bless`). Every mode is checked against the same
/// inline expectations *and* the committed golden, so `memory` and `file` are
/// proven identical to each other and to the reference (TST-021).
fn run_case(case: &Case, golden: &Golden, bless: bool) -> Result<Vec<Value>, String> {
    let modes: &[Mode] = match case.mode.as_str() {
        "both" => &[Mode::Memory, Mode::File],
        "memory" => &[Mode::Memory],
        "file" => &[Mode::File],
        other => return Err(format!("unknown mode {other:?}")),
    };
    let expected = golden.get(&case.id);
    let mut canonical = Vec::new();
    for (m, &mode) in modes.iter().enumerate() {
        let observed = run_case_in_mode(case, mode, expected, bless)?;
        if m == 0 {
            canonical = observed; // the reference mode's observations
        }
    }
    Ok(canonical)
}

#[derive(Clone, Copy, PartialEq)]
enum Mode {
    Memory,
    File,
}

/// Execute a case's steps in one mode, returning each step's canonical
/// observation (`{"error": CODE}` for a failing step). Checks the inline
/// `expect` and, when `golden` is present, deep-compares against it (1e-5).
fn run_case_in_mode(
    case: &Case,
    mode: Mode,
    golden: Option<&Vec<Value>>,
    bless: bool,
) -> Result<Vec<Value>, String> {
    let tmp = match mode {
        Mode::Memory => None,
        Mode::File => Some(TempDb::new(&case.id)?),
    };
    let path = tmp.as_ref().map(|t| t.path.clone());
    let mut db = open_db(mode, path.as_deref())?;

    let mut observations = Vec::new();
    for (i, step) in case.steps.iter().enumerate() {
        let where_ = format!("step {i} `{}`", step.op);

        // `reopen` is a runner control op, not a core call — no observation.
        if step.op == "reopen" {
            let Some(p) = &path else {
                return Err(format!("{where_}: reopen requires file mode"));
            };
            db.checkpoint()
                .map_err(|e| format!("{where_}: checkpoint: {e}"))?;
            drop(db);
            db = open_db(mode, Some(p))?;
            continue;
        }

        let outcome = execute(&db, &step.op, &step.args);

        // Inline, human-authored assertions (ids, error, result, value, cursor).
        if let Some(expect) = &step.expect {
            check(expect, &outcome).map_err(|e| format!("{where_}: {e}"))?;
        } else if let Err(code) = &outcome {
            return Err(format!("{where_}: unexpected error {code}"));
        }

        // Canonical observation for the golden.
        let obs = match &outcome {
            Ok(v) => v.clone(),
            Err(code) => json!({ "error": code }),
        };

        // Machine golden: pins scores and lossy round-trips across languages.
        if !bless {
            if let Some(g) = golden {
                let want = g.get(observations.len()).ok_or_else(|| {
                    format!("{where_}: golden has no entry for this step (re-bless the corpus)")
                })?;
                if !json_eq_tol(want, &obs, SCORE_TOL) {
                    return Err(format!(
                        "{where_}: golden mismatch: expected {want}, got {obs}"
                    ));
                }
            }
        }
        observations.push(obs);
    }
    Ok(observations)
}

fn open_db(mode: Mode, path: Option<&Path>) -> Result<VecLite, String> {
    match (mode, path) {
        (Mode::Memory, _) => Ok(VecLite::memory()),
        (Mode::File, Some(p)) => {
            VecLite::open_with(p, OpenOptions::new().durability(Durability::Full))
                .map_err(|e| format!("open {}: {e}", p.display()))
        }
        (Mode::File, None) => Err("file mode without a path".to_owned()),
    }
}

/// A temp-file db path cleaned up on drop (db + sidecar WAL).
struct TempDb {
    path: PathBuf,
}
impl TempDb {
    fn new(case_id: &str) -> Result<Self, String> {
        let mut dir = std::env::temp_dir();
        let slug: String = case_id
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
            .collect();
        dir.push(format!(
            "veclite-conf-{}-{slug}.veclite",
            std::process::id()
        ));
        // Start clean in case a prior aborted run left a file behind.
        cleanup(&dir);
        Ok(TempDb { path: dir })
    }
}
impl Drop for TempDb {
    fn drop(&mut self) {
        cleanup(&self.path);
    }
}
fn cleanup(db: &Path) {
    let _ = std::fs::remove_file(db);
    let mut wal = db.file_name().unwrap_or_default().to_os_string();
    wal.push("-wal");
    let _ = std::fs::remove_file(db.with_file_name(wal));
}

// ── Operation dispatch ───────────────────────────────────────────────────────

/// Execute one operation, returning a canonical observation object on success or
/// the VecLite error `code` string on failure. The observation shape is shared
/// with the Python/Node runners: `{ids,scores}`, `{result}`, `{value}`, etc.
fn execute(db: &VecLite, op: &str, args: &Value) -> Result<Value, String> {
    match op {
        "create_collection" => op_create_collection(db, args),
        "delete_collection" => db
            .delete_collection(sget_str(args, "name")?)
            .map(|()| json!({}))
            .map_err(code_string),
        "list_collections" => Ok(json!({ "ids": db.list_collections() })),
        "create_alias" => db
            .create_alias(sget_str(args, "alias")?, sget_str(args, "target")?)
            .map(|()| json!({}))
            .map_err(code_string),
        "delete_alias" => db
            .delete_alias(sget_str(args, "alias")?)
            .map(|()| json!({}))
            .map_err(code_string),
        "upsert" => op_upsert(db, args),
        "upsert_batch" => op_upsert_batch(db, args),
        "upsert_text" => op_upsert_text(db, args),
        "refit" => coll(db, args)?
            .refit()
            .map(|()| json!({}))
            .map_err(code_string),
        "get" => op_get(db, args),
        "delete" => coll(db, args)?
            .delete(sget_str(args, "id")?)
            .map(|b| json!({ "value": b }))
            .map_err(code_string),
        "len" => Ok(json!({ "value": coll(db, args)?.len() })),
        "stats" => op_stats(db, args),
        "search" => op_search(db, args),
        "search_text" => op_search_text(db, args),
        "hybrid_search" => op_hybrid(db, args),
        "scroll" => op_scroll(db, args),
        "chunk" => op_chunk(args),
        other => Err(format!("__runner__: unknown op {other:?}")),
    }
}

/// Resolve a collection handle by the step's `collection` arg (may error with a
/// core code, e.g. `COLLECTION_NOT_FOUND`, which the corpus can assert).
fn coll(db: &VecLite, args: &Value) -> Result<veclite::Collection, String> {
    db.collection(sget_str(args, "collection")?)
        .map_err(code_string)
}

fn op_create_collection(db: &VecLite, args: &Value) -> Result<Value, String> {
    let name = sget_str(args, "name")?;
    let dim = uget(args, "dimension")?;
    let mut opts = match args.get("auto_embed").and_then(Value::as_str) {
        Some(provider) => CollectionOptions::auto_embed(provider, dim),
        None => CollectionOptions::new(dim, metric_of(args.get("metric").and_then(Value::as_str))?),
    };
    if let Some(bits) = args.get("quantization_bits").and_then(Value::as_u64) {
        opts = opts.quantization(if bits == 0 {
            Quantization::None
        } else {
            Quantization::Scalar { bits: bits as u8 }
        });
    }
    if let Some(h) = args.get("hnsw") {
        let d = HnswOptions::default();
        let g = |k: &str, def: usize| h.get(k).and_then(Value::as_u64).map_or(def, |v| v as usize);
        opts = opts.hnsw(
            g("m", d.m),
            g("ef_construction", d.ef_construction),
            g("ef_search", d.ef_search),
        );
    }
    if let Some(idxs) = args.get("payload_indexes").and_then(Value::as_array) {
        for pair in idxs {
            let key = pair
                .get(0)
                .and_then(Value::as_str)
                .ok_or("payload index needs a key")?;
            let kind = pair
                .get(1)
                .and_then(Value::as_str)
                .ok_or("payload index needs a kind")?;
            opts = opts.payload_index(key, payload_index_kind(kind)?);
        }
    }
    db.create_collection(name, opts)
        .map(|_| json!({}))
        .map_err(code_string)
}

fn op_upsert(db: &VecLite, args: &Value) -> Result<Value, String> {
    let c = coll(db, args)?;
    c.upsert(point_of(args)?)
        .map(|()| json!({}))
        .map_err(code_string)
}

fn op_upsert_batch(db: &VecLite, args: &Value) -> Result<Value, String> {
    let c = coll(db, args)?;
    let rows = args
        .get("points")
        .and_then(Value::as_array)
        .ok_or("upsert_batch needs `points`")?;
    let points: Result<Vec<Point>, String> = rows.iter().map(point_of).collect();
    c.upsert_batch(points?)
        .map(|()| json!({}))
        .map_err(code_string)
}

fn op_upsert_text(db: &VecLite, args: &Value) -> Result<Value, String> {
    let c = coll(db, args)?;
    let id = sget_str(args, "id")?;
    let text = sget_str(args, "text")?;
    match args.get("payload").filter(|p| !p.is_null()) {
        Some(p) => c.upsert_text_with(id, text, p.clone()),
        None => c.upsert_text(id, text),
    }
    .map(|()| json!({}))
    .map_err(code_string)
}

fn op_get(db: &VecLite, args: &Value) -> Result<Value, String> {
    let c = coll(db, args)?;
    let got = c.get(sget_str(args, "id")?).map_err(code_string)?;
    let result = match got {
        None => Value::Null,
        Some(p) => json!({ "id": p.id, "vector": p.vector, "payload": p.payload }),
    };
    Ok(json!({ "result": result }))
}

fn op_stats(db: &VecLite, args: &Value) -> Result<Value, String> {
    let s = coll(db, args)?.stats();
    Ok(json!({ "value": {
        "dimension": s.dimension,
        "len": s.len,
        "tombstones": s.tombstones,
        "auto_embed": s.auto_embed,
    }}))
}

fn op_search(db: &VecLite, args: &Value) -> Result<Value, String> {
    let c = coll(db, args)?;
    let v = fvec(args, "vector")?;
    let mut q = c.query(&v);
    if let Some(l) = args.get("limit").and_then(Value::as_u64) {
        q = q.limit(l as usize);
    }
    if let Some(ef) = args.get("ef_search").and_then(Value::as_u64) {
        q = q.ef_search(ef as usize);
    }
    if let Some(wp) = args.get("with_payload").and_then(Value::as_bool) {
        q = q.with_payload(wp);
    }
    if let Some(wv) = args.get("with_vector").and_then(Value::as_bool) {
        q = q.with_vector(wv);
    }
    if let Some(f) = args.get("filter").filter(|f| !f.is_null()) {
        q = q.filter(Filter::from_json(f).map_err(code_string)?);
    }
    let hits = q.run().map_err(code_string)?;
    Ok(hits_observation(hits))
}

fn op_search_text(db: &VecLite, args: &Value) -> Result<Value, String> {
    let c = coll(db, args)?;
    let limit = args.get("limit").and_then(Value::as_u64).unwrap_or(10) as usize;
    let hits = c
        .search_text(sget_str(args, "query")?, limit)
        .map_err(code_string)?;
    Ok(hits_observation(hits))
}

fn op_hybrid(db: &VecLite, args: &Value) -> Result<Value, String> {
    let c = coll(db, args)?;
    let dense = args
        .get("dense")
        .filter(|d| !d.is_null())
        .map(|_| fvec(args, "dense"))
        .transpose()?;
    let sparse = match args.get("sparse").filter(|s| !s.is_null()) {
        Some(s) => Some(sparse_of(s)?),
        None => None,
    };
    let mut q = c.hybrid_query();
    if let Some(d) = &dense {
        q = q.dense(d);
    }
    if let Some(s) = &sparse {
        q = q.sparse(s);
    }
    if let Some(a) = args.get("alpha").and_then(Value::as_f64) {
        q = q.alpha(a as f32);
    }
    if let Some(k) = args.get("rrf_k").and_then(Value::as_f64) {
        q = q.rrf_k(k as f32);
    }
    if let Some(l) = args.get("limit").and_then(Value::as_u64) {
        q = q.limit(l as usize);
    }
    let hits = q.run().map_err(code_string)?;
    Ok(hits_observation(hits))
}

fn op_scroll(db: &VecLite, args: &Value) -> Result<Value, String> {
    let c = coll(db, args)?;
    let limit = args.get("limit").and_then(Value::as_u64).unwrap_or(100) as usize;
    let offset = args.get("offset_id").and_then(Value::as_str);
    let filter = match args.get("filter").filter(|f| !f.is_null()) {
        Some(f) => Some(Filter::from_json(f).map_err(code_string)?),
        None => None,
    };
    let page = c
        .scroll(offset, limit, filter.as_ref())
        .map_err(code_string)?;
    let ids: Vec<String> = page.points.iter().map(|p| p.id.clone()).collect();
    Ok(json!({ "ids": ids, "next_cursor": page.next_cursor }))
}

fn op_chunk(args: &Value) -> Result<Value, String> {
    let text = sget_str(args, "text")?;
    let d = ChunkOptions::default();
    let opts = ChunkOptions {
        max_chars: args
            .get("max_chars")
            .and_then(Value::as_u64)
            .map_or(d.max_chars, |v| v as usize),
        overlap: args
            .get("overlap")
            .and_then(Value::as_u64)
            .map_or(d.overlap, |v| v as usize),
    };
    let chunks: Vec<Value> = Chunker::new(opts)
        .chunk(text)
        .into_iter()
        .map(|c| json!({ "text": c.text, "start": c.byte_range.start, "end": c.byte_range.end }))
        .collect();
    Ok(json!({ "result": chunks }))
}

/// Project ranked hits to the shared `{ids, scores}` observation.
fn hits_observation(hits: Vec<veclite::Hit>) -> Value {
    let ids: Vec<String> = hits.iter().map(|h| h.id.clone()).collect();
    let scores: Vec<f64> = hits.iter().map(|h| f64::from(h.score)).collect();
    json!({ "ids": ids, "scores": scores })
}

// ── Arg helpers ──────────────────────────────────────────────────────────────

fn sget_str<'a>(args: &'a Value, key: &str) -> Result<&'a str, String> {
    args.get(key)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("missing string arg `{key}`"))
}

fn uget(args: &Value, key: &str) -> Result<usize, String> {
    args.get(key)
        .and_then(Value::as_u64)
        .map(|v| v as usize)
        .ok_or_else(|| format!("missing integer arg `{key}`"))
}

/// Read a `float32` vector arg (YAML numbers, ints or floats).
fn fvec(args: &Value, key: &str) -> Result<Vec<f32>, String> {
    let arr = args
        .get(key)
        .and_then(Value::as_array)
        .ok_or_else(|| format!("missing vector arg `{key}`"))?;
    arr.iter()
        .map(|n| {
            n.as_f64()
                .map(|f| f as f32)
                .ok_or_else(|| format!("`{key}` has a non-number"))
        })
        .collect()
}

fn sparse_of(v: &Value) -> Result<SparseVector, String> {
    serde_json::from_value(v.clone()).map_err(|e| format!("invalid sparse vector: {e}"))
}

/// Build a `Point` from `{id, vector, payload?, sparse?}`.
fn point_of(args: &Value) -> Result<Point, String> {
    let id = sget_str(args, "id")?;
    let mut p = Point::new(id, fvec(args, "vector")?);
    if let Some(payload) = args.get("payload").filter(|p| !p.is_null()) {
        p = p.payload(payload.clone());
    }
    if let Some(s) = args.get("sparse").filter(|s| !s.is_null()) {
        p = p.sparse(sparse_of(s)?);
    }
    Ok(p)
}

fn metric_of(s: Option<&str>) -> Result<Metric, String> {
    Ok(match s {
        None | Some("cosine") => Metric::Cosine,
        Some("euclidean") | Some("l2") => Metric::Euclidean,
        Some("dot") | Some("dotproduct") | Some("dot_product") => Metric::DotProduct,
        Some(other) => return Err(format!("unknown metric {other:?}")),
    })
}

fn payload_index_kind(s: &str) -> Result<PayloadIndexKind, String> {
    Ok(match s {
        "keyword" => PayloadIndexKind::Keyword,
        "integer" => PayloadIndexKind::Integer,
        "float" => PayloadIndexKind::Float,
        other => return Err(format!("unknown payload index kind {other:?}")),
    })
}

/// The stable error `code` for a `VecLiteError` — identical to the FFI/Node
/// codes so a corpus `error:` assertion is language-independent.
fn code_string(e: VecLiteError) -> String {
    let code = match e {
        VecLiteError::CollectionNotFound(_) => "COLLECTION_NOT_FOUND",
        VecLiteError::VectorNotFound(_) => "VECTOR_NOT_FOUND",
        VecLiteError::AlreadyExists(_) => "ALREADY_EXISTS",
        VecLiteError::DimensionMismatch { .. } => "DIMENSION_MISMATCH",
        VecLiteError::Locked => "LOCKED",
        VecLiteError::WalPending => "WAL_PENDING",
        VecLiteError::ReadOnly => "READ_ONLY",
        VecLiteError::Closed => "CLOSED",
        VecLiteError::Corrupt(_) => "CORRUPT",
        VecLiteError::UnsupportedFormatVersion { .. } => "UNSUPPORTED_FORMAT_VERSION",
        VecLiteError::UnsupportedProvider { .. } => "UNSUPPORTED_PROVIDER",
        VecLiteError::InvalidArgument(_) => "INVALID_ARGUMENT",
        VecLiteError::Io(_) => "IO",
        _ => "ERROR",
    };
    code.to_owned()
}

// ── Expectation checking & blessing ──────────────────────────────────────────

/// Compare an `expect` object against an operation outcome. `error` asserts the
/// failure code; any other present key is deep-compared (numeric tolerance
/// 1e-5) against the same key in the success observation.
fn check(expect: &Value, outcome: &Result<Value, String>) -> Result<(), String> {
    let expect = expect.as_object().ok_or("`expect` must be a mapping")?;

    if let Some(code) = expect.get("error").and_then(Value::as_str) {
        return match outcome {
            Err(got) if got == code => Ok(()),
            Err(got) => Err(format!("expected error {code}, got {got}")),
            Ok(v) => Err(format!("expected error {code}, but op succeeded with {v}")),
        };
    }

    let obs = match outcome {
        Ok(v) => v,
        Err(code) => return Err(format!("unexpected error {code}")),
    };
    for (key, want) in expect {
        let got = obs.get(key).unwrap_or(&Value::Null);
        if !matches_subset(want, got, SCORE_TOL) {
            return Err(format!("`{key}`: expected {want}, got {got}"));
        }
    }
    Ok(())
}

/// Like [`json_eq_tol`] but object comparison is a *subset* match: every key in
/// `want` must be present and match in `got`, while extra keys in `got` are
/// ignored. Inline `expect` values assert only what they name (e.g. `stats`
/// asserts `len` without pinning `tombstones`); the golden pins the rest.
fn matches_subset(want: &Value, got: &Value, tol: f64) -> bool {
    match (want, got) {
        (Value::Object(w), Value::Object(g)) => w
            .iter()
            .all(|(k, wv)| g.get(k).is_some_and(|gv| matches_subset(wv, gv, tol))),
        (Value::Array(ws), Value::Array(gs)) => {
            ws.len() == gs.len() && ws.iter().zip(gs).all(|(w, g)| matches_subset(w, g, tol))
        }
        (Value::Number(x), Value::Number(y)) => match (x.as_f64(), y.as_f64()) {
            (Some(fx), Some(fy)) => (fx - fy).abs() <= tol,
            _ => x == y,
        },
        _ => want == got,
    }
}

/// Deep JSON equality where numbers compare as f64 within `tol` (so YAML ints
/// match f32 outputs and scores match within 1e-5); strings/bools/null exact.
fn json_eq_tol(a: &Value, b: &Value, tol: f64) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => match (x.as_f64(), y.as_f64()) {
            (Some(fx), Some(fy)) => (fx - fy).abs() <= tol,
            _ => x == y,
        },
        (Value::Array(xs), Value::Array(ys)) => {
            xs.len() == ys.len() && xs.iter().zip(ys).all(|(x, y)| json_eq_tol(x, y, tol))
        }
        (Value::Object(xo), Value::Object(yo)) => {
            xo.len() == yo.len()
                && xo
                    .iter()
                    .all(|(k, xv)| yo.get(k).is_some_and(|yv| json_eq_tol(xv, yv, tol)))
        }
        _ => a == b,
    }
}
