//! Retrieval-quality gates (SPEC-001 §5–6): HNSW recall vs brute force, SQ-8
//! reconstruction recall, and soft-delete/over-fetch correctness.
//!
//! These exercise `Collection::search_internal` and the vendored quantization,
//! both of which are native-only or need crate-internal access, so this is an
//! in-crate `#[cfg(test)]` module rather than an integration test. The corpus
//! is generated by a fixed-seed splitmix64 so the gates are deterministic
//! without pulling in `rand`.

use crate::options::{CollectionOptions, Metric, Quantization};
use crate::point::Point;
use crate::quantization::ScalarQuantization;
use crate::quantization::traits::QuantizationMethod;
use crate::simd::euclidean_distance;
use crate::{Collection, VecLite};

/// Deterministic splitmix64 — enough for reproducible test corpora.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Rng(seed)
    }

    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Uniform component in `[-1, 1)`.
    #[allow(clippy::cast_precision_loss)]
    fn next_component(&mut self) -> f32 {
        let unit = (self.next_u64() >> 40) as f32 / (1u64 << 24) as f32;
        unit * 2.0 - 1.0
    }
}

fn corpus(rng: &mut Rng, n: usize, dim: usize) -> Vec<Vec<f32>> {
    (0..n)
        .map(|_| (0..dim).map(|_| rng.next_component()).collect())
        .collect()
}

/// Brute-force top-`k` slot indices by Euclidean distance (the recall oracle).
fn brute_force_top_k(vectors: &[Vec<f32>], query: &[f32], k: usize) -> Vec<usize> {
    let mut scored: Vec<(usize, f32)> = vectors
        .iter()
        .enumerate()
        .map(|(i, v)| (i, euclidean_distance(query, v)))
        .collect();
    scored.sort_by(|a, b| a.1.total_cmp(&b.1));
    scored.into_iter().take(k).map(|(i, _)| i).collect()
}

fn recall(expected: &[usize], got: &[String]) -> f32 {
    let got_ids: std::collections::HashSet<&str> = got.iter().map(String::as_str).collect();
    let hits = expected
        .iter()
        .filter(|&&i| got_ids.contains(format!("v{i}").as_str()))
        .count();
    #[allow(clippy::cast_precision_loss)]
    {
        hits as f32 / expected.len() as f32
    }
}

fn seeded_collection(n: usize, dim: usize, vectors: &[Vec<f32>]) -> Collection {
    let db = VecLite::memory();
    let c = db
        .create_collection(
            "gate",
            CollectionOptions::new(dim, Metric::Euclidean).quantization(Quantization::None),
        )
        .unwrap_or_else(|e| panic!("{e}"));
    for (i, v) in vectors.iter().enumerate().take(n) {
        c.upsert(Point::new(format!("v{i}"), v.clone()))
            .unwrap_or_else(|e| panic!("{e}"));
    }
    c
}

/// Task 2.1 — HNSW top-10 recall vs brute force must be >= 0.95 at defaults.
#[test]
fn hnsw_recall_matches_brute_force() {
    const N: usize = 1000;
    const DIM: usize = 16;
    const K: usize = 10;
    const QUERIES: usize = 40;

    let mut rng = Rng::new(0x5EED_1234_ABCD_0001);
    let vectors = corpus(&mut rng, N, DIM);
    let c = seeded_collection(N, DIM, &vectors);

    let mut total = 0.0f32;
    for _ in 0..QUERIES {
        let query: Vec<f32> = (0..DIM).map(|_| rng.next_component()).collect();
        let expected = brute_force_top_k(&vectors, &query, K);
        let got = c
            .search_internal(&query, K, 256)
            .unwrap_or_else(|e| panic!("{e}"));
        assert_eq!(got.len(), K, "index returned fewer than k live results");
        let got_ids: Vec<String> = got.into_iter().map(|(id, _)| id).collect();
        total += recall(&expected, &got_ids);
    }
    let avg = total / QUERIES as f32;
    assert!(avg >= 0.95, "top-{K} HNSW recall {avg} < 0.95");
}

/// Task 2.2 — SQ-8 reconstruction top-10 recall vs unquantized must be >= 0.99.
#[test]
fn sq8_recall_matches_unquantized() {
    const N: usize = 1500;
    const DIM: usize = 32;
    const K: usize = 10;
    const QUERIES: usize = 40;

    let mut rng = Rng::new(0x5EED_1234_ABCD_0002);
    let vectors = corpus(&mut rng, N, DIM);

    // Fit + quantize + dequantize the whole corpus (batch fit — CORE-041).
    let mut sq = ScalarQuantization::new(8).unwrap_or_else(|e| panic!("{e}"));
    sq.fit(&vectors).unwrap_or_else(|e| panic!("{e}"));
    let quantized = sq.quantize(&vectors).unwrap_or_else(|e| panic!("{e}"));
    let restored = sq.dequantize(&quantized).unwrap_or_else(|e| panic!("{e}"));

    let mut total = 0.0f32;
    for _ in 0..QUERIES {
        let query: Vec<f32> = (0..DIM).map(|_| rng.next_component()).collect();
        let expected = brute_force_top_k(&vectors, &query, K);
        let got_slots = brute_force_top_k(&restored, &query, K);
        let got_ids: Vec<String> = got_slots.iter().map(|i| format!("v{i}")).collect();
        total += recall(&expected, &got_ids);
    }
    let avg = total / QUERIES as f32;
    assert!(avg >= 0.99, "SQ-8 top-{K} recall {avg} < 0.99");
}

/// Task 2.3 — after deleting half the collection, search returns only live
/// vectors and still fills the limit (soft-delete + over-fetch, CORE-032).
#[test]
fn search_excludes_tombstoned_slots() {
    const N: usize = 600;
    const DIM: usize = 16;
    const K: usize = 10;
    const QUERIES: usize = 20;

    let mut rng = Rng::new(0x5EED_1234_ABCD_0003);
    let vectors = corpus(&mut rng, N, DIM);
    let c = seeded_collection(N, DIM, &vectors);

    // Delete every even id; odd ids stay live (N/2 of them, >> K).
    for i in (0..N).step_by(2) {
        assert!(
            c.delete(&format!("v{i}")).unwrap_or_else(|e| panic!("{e}")),
            "expected v{i} to exist before deletion"
        );
    }
    assert_eq!(c.len(), N / 2);

    for _ in 0..QUERIES {
        let query: Vec<f32> = (0..DIM).map(|_| rng.next_component()).collect();
        let got = c
            .search_internal(&query, K, 256)
            .unwrap_or_else(|e| panic!("{e}"));
        assert_eq!(
            got.len(),
            K,
            "over-fetch failed to fill the limit with live results"
        );
        for (id, _) in &got {
            let idx: usize = id
                .strip_prefix('v')
                .and_then(|s| s.parse().ok())
                .unwrap_or_else(|| panic!("unexpected id {id}"));
            assert_eq!(idx % 2, 1, "tombstoned (even) id {id} leaked into results");
        }
    }
}

/// `reindex` rebuilds the graph from live vectors and computes SQ-8 codes over
/// the live set; search still works and tombstones are gone from the graph
/// (CORE-032). Also covers the `Quantization::Scalar` code path in `reindex`.
#[test]
fn reindex_purges_tombstones_and_encodes() {
    const N: usize = 400;
    const DIM: usize = 16;

    let mut rng = Rng::new(0x5EED_1234_ABCD_0004);
    let vectors = corpus(&mut rng, N, DIM);
    let db = VecLite::memory();
    let c = db
        .create_collection(
            "reindexed",
            CollectionOptions::new(DIM, Metric::Euclidean)
                .quantization(Quantization::Scalar { bits: 8 }),
        )
        .unwrap_or_else(|e| panic!("{e}"));
    for (i, v) in vectors.iter().enumerate() {
        c.upsert(Point::new(format!("v{i}"), v.clone()))
            .unwrap_or_else(|e| panic!("{e}"));
    }
    for i in (0..N).step_by(3) {
        c.delete(&format!("v{i}")).unwrap_or_else(|e| panic!("{e}"));
    }
    c.reindex().unwrap_or_else(|e| panic!("{e}"));

    let live = c.len();
    let query: Vec<f32> = (0..DIM).map(|_| rng.next_component()).collect();
    let got = c
        .search_internal(&query, 5, 128)
        .unwrap_or_else(|e| panic!("{e}"));
    assert_eq!(got.len(), 5);
    for (id, _) in &got {
        let idx: usize = id
            .strip_prefix('v')
            .and_then(|s| s.parse().ok())
            .unwrap_or_else(|| panic!("unexpected id {id}"));
        assert_ne!(
            idx % 3,
            0,
            "reindex left a tombstoned slot in the graph: {id}"
        );
    }
    assert_eq!(live, N - N.div_ceil(3));
}
